name: TonyVR
favicon: null
layout_spectrum: 0.0496187771204859
typography_spectrum: 0.4022566070780158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9d9b5'
    - '#ae9d7f'
    - '#4e4633'
    - '#0d080c'
    - '#44a86c'
  brandStrength: 0.75
  lightness: 0.37842649896629155
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
