name: TonvanRijswijk
favicon: null
layout_spectrum: 0.22007
typography_spectrum: 0.85577
title: TONY VR
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbfc'
    - '#118c55'
    - '#abb1ba'
    - '#161614'
    - '#d52d54'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
