name: TonyvanRijswijk
favicon: null
layout_spectrum: 0.0496187771204859
typography_spectrum: 0.4022566070780158
title: TONYVR
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbfc'
    - '#118c55'
    - '#abb1ba'
    - '#161614'
    - '#d52d54'
  brandStrength: 0
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 1
purpose: []
